### ISSUE TITLE
create see_also links in schema pointing to obook pages

### ISSUE THREAD

**Issue by cmungall** [INCATools/kgcl-rdflib#33]
Currently we have links to GO wiki pages:

```yaml
  node creation:
    is_a: node change
    mixins:
      - creation
    description: >-
      a node change in which a new node is created
    slots:
      - node id
      - name
      - owl type
      - annotation set
      - language
    slot_usage:
      change description:
        string_serialization: "creating node {id} {label} with {annotation set}"
    todos:
      - allow this for the creation of an instance from a class. This may include metaclasses (templates)
    see_also:
      - http://wiki.geneontology.org/index.php/Guidelines_for_creating_a_GO_term
```

these should remain, but we should also point to the relevant obook page

in this case, https://oboacademy.github.io/obook/howto/create-new-term/

Note there are some ODK pages that are becoming obsolete, see

 - https://github.com/INCATools/ontology-development-kit/pull/578
